on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_job:
    name: python
    runs-on: ubuntu-latest
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    strategy:
      matrix:
        python-version:
          - "3.11"
          # Could check more versions if issues arrise
          # - "3.12"
          # - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Pyright
        run: uv tool run pyright

      # Might not be needed.
      # - uses: jakebailey/pyright-action@v2
      #   with:
      #     version: 1.1.311

      - name: Minimize uv cache
        run: uv cache prune --ci
